apiVersion: v1
kind: Service
metadata:
  name: taskservice
spec:
  # This creates an AWS Load Balancer
  type: LoadBalancer
  selector:
    app: taskservice       # Must match the 'app: taskservice' label in your Deployment YAML
  ports:
    - protocol: TCP
      port: 80             # The port exposed on the Load Balancer
      targetPort: 8080     # The port your Spring Boot app is listening on
---
apiVersion: v1
kind: Service
metadata:
  name: projectservice
spec:
  type: LoadBalancer
  selector:
    app: projectservice
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: reportservice
spec:
  type: LoadBalancer
  selector:
    app: reportservice
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080